{ config, lib, pkgs, ... }:
let
  inherit (lib) mkDefault mkOption types;
  rust = pkgs.rust-bin.fromRustupToolchainFile ../rust-toolchain.toml;

  shellPath = path:
    lib.optionalString (!(lib.hasPrefix "/" path)) ''"$PROJECT_ROOT"/''
    + lib.escapeShellArg path;

  generateToml = name: settings:
    let source = (pkgs.formats.toml { }).generate name settings;
    in pkgs.runCommand name { } ''
      echo '# Generated by Nix; edit the Nix modules, not this file.' > "$out"
      cat ${source} >> "$out"
    '';

  setup = ''
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: value: ''
      if [[ ! -v ${name} ]]; then
        # Module values are literal strings, including any dollar signs.
        # shellcheck disable=SC2016,SC2089
        ${name}=${lib.escapeShellArg value}
      fi
      # shellcheck disable=SC2090
      export ${name}
    '') config.development.environment)}
    PROJECT_ROOT="''${PROJECT_ROOT:-$(${pkgs.git}/bin/git rev-parse --show-toplevel)}"
    export PROJECT_ROOT
    # Resolve relative paths at runtime and quote the configured literal path.
    # shellcheck disable=SC2016,SC2089
    PROJECT_STATE=${shellPath config.development.stateDirectory}
    # shellcheck disable=SC2090
    export PROJECT_STATE
    ${pkgs.coreutils}/bin/mkdir -p "$PROJECT_STATE"
    ${config.development.shellHook}
  '';

  mkCommand = { name, directory ? "", text, runtimeInputs ? [ ] }:
    pkgs.writeShellApplication {
      inherit name runtimeInputs;
      text = lib.optionalString (directory != "") ''
        cd "$PROJECT_ROOT/${directory}"
      '' + text;
    };
in
{
  options = {
    development = {
      stateDirectory = mkOption {
        type = types.str;
        default = ".state";
        description = "Shared state directory, absolute or relative to PROJECT_ROOT.";
      };
      packages = mkOption {
        type = types.listOf types.package;
        default = [ ];
        description = "Tools available in the development shell and commands.";
      };
      buildInputs = mkOption {
        type = types.listOf types.package;
        default = [ ];
        description = "Libraries initialized by the development shell's setup hooks.";
      };
      environment = mkOption {
        type = types.attrsOf types.str;
        default = { };
        description = "Environment defaults; existing shell variables take precedence.";
      };
      shellHook = mkOption {
        type = types.lines;
        default = "";
        description = "Runtime initialization performed once when entering the development shell.";
      };
      commands = mkOption {
        type = types.attrsOf types.package;
        default = { };
        description = "Executable packages exposed through nix run and the development shell.";
      };
    };
    generatedFiles = mkOption {
      type = types.attrsOf types.package;
      default = { };
      internal = true;
      description = "Generated configuration files keyed by repository-relative path.";
    };
    outputs.devShell = mkOption {
      type = types.package;
      internal = true;
      description = "The development shell with all commands and tools.";
    };
  };

  config = {
    _module.args = { inherit mkCommand shellPath generateToml; };
    development.packages = [ rust pkgs.git pkgs.pkg-config ];
    development.buildInputs = lib.optionals pkgs.stdenv.hostPlatform.isDarwin [ pkgs.libiconv ];

    settings = {
      disable_env_expansion = mkDefault false;
      ordered_shutdown = mkDefault true;
    };
    cli = {
      environment.PC_DISABLE_DOTENV = true;
      preHook = ''
        cd "$PROJECT_ROOT"
      '';
    };

    outputs.devShell = pkgs.mkShell {
      inherit (config.development) buildInputs;
      packages = config.development.packages ++ lib.attrValues config.development.commands ++ [
        config.outputs.package
        pkgs.direnv
        pkgs.nix-direnv
      ];
      shellHook = setup;
    };
  };
}
