[package]
name = "shrimpman-sign"
version.workspace = true
edition.workspace = true

[dependencies]
automod = "1"
argon2 = { version = "0.5", features = ["std"] }
async-trait = "0.1"
binrw = "0.15"
bytes = "1"
config = { version = "0.15", default-features = false, features = ["toml"] }
futures-util = { version = "0.3", features = ["sink"] }
inventory = "0.3"
jiff = { version = "0.2", features = ["serde"] }
rand = "0.10"
serde = { version = "1", features = ["derive"] }
sha2 = "0.11"
shrimpman-common = { path = "../common" }
shrimpman-config = { path = "../config" }
shrimpman-domain = { path = "../domain" }
shrimpman-discovery = { path = "../discovery" }
shrimpman-persistence = { path = "../persistence" }
shrimpman-protocol = { path = "../protocol" }
shrimpman-transport = { path = "../transport" }
thiserror = "2"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
toasty = { version = "0.10", features = ["sqlite"] }
tracing = "0.1"
