[migration]
database_url = "sqlite://shrimpman.sqlite3"

[sign]
auto_sign_up = false

[sign.database]
url = "sqlite://shrimpman.sqlite3"

[sign.discovery]
endpoints = ["http://127.0.0.1:2379"]
lease_ttl = "15s"
reconnect_delay = "1s"

[sign.session]
ttl = "5m"

[sign.server]
listen_addr = "0.0.0.0:53312"
advertise_addr = "127.0.0.1:53312"
shutdown_timeout = "5s"
