[migration]
database_url = "sqlite://shrimpman.sqlite3"

[entrance.lease_kv]
endpoints = ["http://127.0.0.1:2379"]
lease_ttl = "15s"
reconnect_delay = "1s"

[entrance.logging]
filter = "warn,shrimpman_entrance=info,shrimpman_discovery=info,shrimpman_lease_kv=info,shrimpman_transport=debug"

[entrance.server]
listen_addr = "0.0.0.0:53310"
advertise_addr = "127.0.0.1:53310"
shutdown_timeout = "5s"

[sign]
auto_sign_up = false

[sign.database]
url = "sqlite://shrimpman.sqlite3"

[sign.lease_kv]
endpoints = ["http://127.0.0.1:2379"]
lease_ttl = "15s"
reconnect_delay = "1s"

[sign.logging]
filter = "warn,shrimpman_sign=info,shrimpman_discovery=info,shrimpman_lease_kv=info"

[sign.session]
ttl = "5m"

[sign.server]
listen_addr = "0.0.0.0:53312"
advertise_addr = "127.0.0.1:53312"
shutdown_timeout = "5s"

[world]
key = "main"
address = "127.0.0.1"
name = "Main World"
description = ""
world_type = "Free"
season = "Breeding"
content = "AllQuests"
client_compatibility = "AllPlatforms"

[world.database]
url = "sqlite://shrimpman.sqlite3"

[world.lease_kv]
endpoints = ["http://127.0.0.1:2379"]
lease_ttl = "15s"
reconnect_delay = "1s"

[world.logging]
filter = "warn,shrimpman_world=info,shrimpman_discovery=info,shrimpman_lease_kv=info,shrimpman_transport=debug"

[[world.lands]]
key = "land-1"
listen_addr = "0.0.0.0:54001"
port = 54001
max_players = 100

[[world.lands]]
key = "land-2"
listen_addr = "0.0.0.0:54002"
port = 54002
max_players = 100
