[package]
name = "shrimpman-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
config = { version = "0.15", default-features = false, features = ["toml"] }
tokio = { version = "1", features = ["macros", "net", "rt", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tokio = { version = "1", features = ["sync"] }
