[package]
name = "example-counter-provider"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
example-counter-sdk = { path = "../counter-sdk" }
mhf-mod-sdk = { path = "../../../crates/runtime/mod-sdk" }

[build-dependencies]
example-counter-sdk = { path = "../counter-sdk", features = ["headers"] }
