[package]
name = "mhf-mod-sdk"
version.workspace = true
edition.workspace = true
description = "Rust lifecycle and host bindings for the public MHF mod C ABI"

[features]
headers = ["mhf-mod-api/headers", "safer-ffi/headers"]

[dependencies]
safer-ffi.workspace = true
mhf-mod-api = { path = "../mod-api" }
