[package]
name = "shrimpman-transport"
version.workspace = true
edition.workspace = true

[dependencies]
binrw = "0.15"
bytes = "1"
futures-util = { version = "0.3", features = ["sink"] }
tokio = { version = "1", features = ["io-util"] }
tokio-util = { version = "0.7", features = ["codec"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
