[package]
name = "mhf-debug-tools"
version.workspace = true
edition.workspace = true
publish = false

[features]
default = []
headers = ["mhf-mod-sdk/headers"]
provider = [
    "dep:rfd",
    "dep:mhf-base", "dep:egui", "dep:egui-hunter", "dep:egui_code_editor", "dep:mhf-font", "dep:mhf-hooks",
    "dep:mhf-mod-host", "dep:mhf-quest", "dep:mhf-ui", "dep:windows", "dep:mhf-monster", "dep:mhf-ai-debug",
    "dep:eframe", "dep:winit",
]

[dependencies]
mhf-resource = { path = "../../shared/resource" }
mhf-mod-sdk = { path = "../../runtime/mod-sdk" }
safer-ffi = { workspace = true, features = ["dyn-traits"] }

[target.'cfg(windows)'.dependencies]
rfd = { workspace = true, optional = true }
mhf-ai-debug = { path = "../../shared/ai-debug", optional = true }
mhf-monster = { path = "../monster", optional = true }
mhf-base = { path = "../base", optional = true }
egui = { workspace = true, optional = true }
egui-hunter = { path = "../../shared/egui-hunter", optional = true }
egui_code_editor = { version = "=0.4.1", optional = true }
eframe = { version = "=0.36.1", default-features = false, features = ["wgpu"], optional = true }
winit = { version = "=0.30.13", default-features = false, optional = true }
mhf-font = { path = "../font", features = ["provider"], optional = true }
mhf-ui = { path = "../ui", features = ["provider"], optional = true }
mhf-quest = { path = "../quest", optional = true }
mhf-hooks = { path = "../../runtime/hooks", optional = true }
mhf-mod-host = { path = "../../runtime/mod-host", optional = true }
windows = { workspace = true, optional = true, features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Threading",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(windows)'.dev-dependencies]
mhf-quest = { path = "../quest", features = ["provider"] }
