[package]
name = "shrimpman-world"
version.workspace = true
edition.workspace = true

[dependencies]
config = { version = "0.15", default-features = false, features = ["toml"] }
serde = { version = "1", features = ["derive"] }
shrimpman-discovery = { path = "../discovery" }
shrimpman-domain = { path = "../domain" }
shrimpman-lease-kv = { path = "../lease-kv" }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
