[package]
name = "shrimpman-persistence"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
config = { version = "0.15", default-features = false, features = ["toml"] }
jiff = "0.2"
shrimpman-config = { path = "../config" }
shrimpman-domain = { path = "../domain" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toasty = { version = "0.10", features = ["jiff", "sqlite"] }
toasty-cli = "0.10"
